import {
	FieldFormat,
	getEntityMetadata,
	isRayfinEntity,
	type EntityClass,
	type FieldMetadata
} from "@microsoft/rayfin-core";
import { isSystemReadOnlyName, resourceSlug } from "../conventions.js";
import type { AdminField, AdminFieldType, AdminResources } from "../types.js";

export type GenerateOptions = {
	entities: readonly EntityClass[];
};

export class GeneratorError extends Error {
	constructor(
		message: string,
		readonly entity?: string,
		readonly field?: string
	) {
		super(message);
		this.name = "GeneratorError";
	}
}

export function extractResources(options: GenerateOptions): AdminResources {
	const resources: AdminResources = {};

	for (const entity of options.entities) {
		if (!isRayfinEntity(entity)) {
			throw new GeneratorError(
				`Unsupported construct: expected a Rayfin @entity() class, got ${String(entity)}`
			);
		}

		const meta = getEntityMetadata(entity);
		const name = meta.name || entity.name;
		const fields: AdminField[] = [];

		for (const [fieldName, fieldMeta] of Object.entries(meta.fields)) {
			if (fieldMeta.relationship) continue;
			fields.push(normalizeField(name, fieldName, fieldMeta));
		}

		resources[name] = {
			name,
			slug: resourceSlug(name),
			fields
		};
	}

	return resources;
}

export function normalizeField(entityName: string, fieldName: string, meta: FieldMetadata<any>): AdminField {
	if (!meta.format) {
		throw new GeneratorError(
			`Unsupported field type on ${entityName}.${fieldName}: missing Rayfin field decorator`,
			entityName,
			fieldName
		);
	}

	const type = mapFormat(entityName, fieldName, meta);
	const primaryKey = fieldName === "id";
	const system = Boolean(meta.isSystemType) || isSystemReadOnlyName(fieldName) || primaryKey;
	const generated = primaryKey || Boolean(meta.isSystemType);

	return {
		name: fieldName,
		type,
		nullable: Boolean(meta.isOptional),
		readOnly: system,
		generated,
		primaryKey,
		enumValues: meta.enum ? [...meta.enum] : undefined
	};
}

function mapFormat(entityName: string, fieldName: string, meta: FieldMetadata<any>): AdminFieldType {
	if (meta.enum) return "enum";

	switch (meta.format) {
		case FieldFormat.Uuid:
		case FieldFormat.Email:
			return "string";
		case FieldFormat.Text: {
			const lower = fieldName.toLowerCase();
			if (["description", "notes", "body", "content", "summary"].some((t) => lower.includes(t))) {
				return "text";
			}
			return "string";
		}
		case FieldFormat.Int:
			return "integer";
		case FieldFormat.Decimal:
			return "decimal";
		case FieldFormat.Boolean:
			return "boolean";
		case FieldFormat.Date:
			return "datetime";
		default:
			throw new GeneratorError(
				`Unsupported decorator/type on ${entityName}.${fieldName}: ${String(meta.format)}`,
				entityName,
				fieldName
			);
	}
}

export function formatResourcesModule(resources: AdminResources): string {
	const orderedKeys = Object.keys(resources).sort((a, b) => a.localeCompare(b));

	const body = orderedKeys
		.map((key) => {
			const resource = resources[key]!;
			const fields = resource.fields
				.map((field) => {
					const lines = [
						`\t\t\tname: ${JSON.stringify(field.name)}`,
						`\t\t\ttype: ${JSON.stringify(field.type)}`,
						`\t\t\tnullable: ${field.nullable}`,
						`\t\t\treadOnly: ${field.readOnly}`,
						`\t\t\tgenerated: ${field.generated}`
					];
					if (field.primaryKey) lines.push(`\t\t\tprimaryKey: true`);
					if (field.enumValues) {
						lines.push(`\t\t\tenumValues: ${JSON.stringify([...field.enumValues])} as const`);
					}
					return `\t\t{\n${lines.join(",\n")}\n\t\t}`;
				})
				.join(",\n");

			return `\t${JSON.stringify(resource.name)}: {\n\t\tname: ${JSON.stringify(resource.name)},\n\t\tslug: ${JSON.stringify(resource.slug)},\n\t\tfields: [\n${fields}\n\t\t]\n\t}`;
		})
		.join(",\n");

	return `/* eslint-disable */
// This file is generated by scripts/generate-admin.ts. Do not edit by hand.

import type { AdminResources } from "../types.js";

export const adminResources = {
${body}
} as const satisfies AdminResources;

export function getResourceBySlug(slug: string) {
\treturn Object.values(adminResources).find((resource) => resource.slug === slug);
}

export function listResourceEntries() {
\treturn Object.values(adminResources).sort((a, b) => a.name.localeCompare(b.name));
}

export function resourceDisplayName(name: string): string {
\treturn name.replace(/([a-z0-9])([A-Z])/g, "$1 $2");
}

export function resourcePluralLabel(name: string): string {
\tconst base = resourceDisplayName(name);
\tconst parts = base.split(" ");
\tconst last = parts[parts.length - 1] ?? base;
\tconst plural = /[^aeiou]y$/i.test(last)
\t\t? last.slice(0, -1) + "ies"
\t\t: /(s|x|z|ch|sh)$/i.test(last)
\t\t\t? last + "es"
\t\t\t: last + "s";
\tparts[parts.length - 1] = plural;
\treturn parts.join(" ");
}
`;
}
